POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
	"username": "emad",
	"password": "emad"
}

###

GET http://localhost:8000/users/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNTQ1OTQyLCJpYXQiOjE3NzI1NDU2NDIsImp0aSI6IjI2OTYxOGQxNDFhMzQxYjdiMjAzYWNjM2Y4ZjA0YTExIiwidXNlcl9pZCI6IjEifQ.K7K106eSobxt1Ss3J_2QlSw-G_hwShQDzBaeVrMmofU
###
GET http://localhost:8000/posts/51424610490175574969660891839749723734/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNTQ1OTQyLCJpYXQiOjE3NzI1NDU2NDIsImp0aSI6IjI2OTYxOGQxNDFhMzQxYjdiMjAzYWNjM2Y4ZjA0YTExIiwidXNlcl9pZCI6IjEifQ.K7K106eSobxt1Ss3J_2QlSw-G_hwShQDzBaeVrMmofU
###

POST http://localhost:8000/posts/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNTQ1OTQyLCJpYXQiOjE3NzI1NDU2NDIsImp0aSI6IjI2OTYxOGQxNDFhMzQxYjdiMjAzYWNjM2Y4ZjA0YTExIiwidXNlcl9pZCI6IjEifQ.K7K106eSobxt1Ss3J_2QlSw-G_hwShQDzBaeVrMmofU
{
	"title": "My First Post",
	"content": "This is the content of my first post."
}