POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
	"username": "t",
	"password": "t"
}

###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
	"username": "e",
	"password": "e"
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
	"username": "emad",
	"password": "emad"
}

###


GET http://localhost:8000/users/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczMzI3MTQ4LCJpYXQiOjE3NzMzMjM1NDgsImp0aSI6IjJjNzFmZmRlODQ3MDQ5Yzk5OWQzMDg2YzI1YzM0YzcwIiwidXNlcl9pZCI6IjMifQ.hfT3LxLkf-zVm4k0GdR85rsa_WtKe8nnvzFfFLSgz4s
###
GET http://localhost:8000/posts/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNTQ4MTIyLCJpYXQiOjE3NzI1NDc4MjIsImp0aSI6IjU0NTBmNjAyYWY2NDRiMDBhOTc1MTgyM2U5M2U1YWExIiwidXNlcl9pZCI6IjMifQ.M_2UtwVZ4yfRR9ik-EMfjTDrmfNWhUS3qRq7Abi5lIk
###

POST http://localhost:8000/posts/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNTQ4MTIyLCJpYXQiOjE3NzI1NDc4MjIsImp0aSI6IjU0NTBmNjAyYWY2NDRiMDBhOTc1MTgyM2U5M2U1YWExIiwidXNlcl9pZCI6IjMifQ.M_2UtwVZ4yfRR9ik-EMfjTDrmfNWhUS3qRq7Abi5lIk

{
	"title": "user",
	"content": "user"
}

###

DELETE http://localhost:8000/posts/b3c47f88-1754-4d7e-bc07-a96a6772bdce/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNTQ4NjkxLCJpYXQiOjE3NzI1NDgzOTEsImp0aSI6IjhkOWQ3ZjA3MDU3NzRkY2ZiYmJiMjRjNzVmMGU3ZDU3IiwidXNlcl9pZCI6IjEifQ.d2vOT7Wdmrs89F1ONnTECJ7RSGwlbrr09tkmNe9cwq0