POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
	"username": "e",
	"password": "e"
}

###

GET http://localhost:8000/users/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNTQ2ODk2LCJpYXQiOjE3NzI1NDY1OTYsImp0aSI6IjExNjdhZGRiZGYxOTQ1ZGRhZmQwYmQ5Y2FlYTdiNGY5IiwidXNlcl9pZCI6IjMifQ.uQJDYrt6LWEEym6aM0ufJiqazNiocYanJ8abPQO_x5U
###
GET http://localhost:8000/posts/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNTQ3MjEwLCJpYXQiOjE3NzI1NDY5MTAsImp0aSI6ImE2NzY3NTA4NWYzOTRhMjE5ZDg4ZGI1NTAxYTM5ZDg3IiwidXNlcl9pZCI6IjMifQ.iaq4gD_lDGZMV3BW_vbLTr3_wp8gF-DMIHO5P1mp5x4
###

POST http://localhost:8000/posts/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNTQ2ODk2LCJpYXQiOjE3NzI1NDY1OTYsImp0aSI6IjExNjdhZGRiZGYxOTQ1ZGRhZmQwYmQ5Y2FlYTdiNGY5IiwidXNlcl9pZCI6IjMifQ.uQJDYrt6LWEEym6aM0ufJiqazNiocYanJ8abPQO_x5U

{
	"title": "My Second Post",
	"content": "This is the content of my second post."
}

###

DELETE http://localhost:8000/posts/95009755-ee62-45ee-afa9-95e05b834cd7/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNTQ3MjEwLCJpYXQiOjE3NzI1NDY5MTAsImp0aSI6ImE2NzY3NTA4NWYzOTRhMjE5ZDg4ZGI1NTAxYTM5ZDg3IiwidXNlcl9pZCI6IjMifQ.iaq4gD_lDGZMV3BW_vbLTr3_wp8gF-DMIHO5P1mp5x4